# Generated by Django 5.0.6 on 2024-05-28 13:58

import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], default='True', max_length=8, verbose_name='Visible')),
                ('category', models.SlugField(editable=False, unique=True, verbose_name='Category')),
                ('name', models.CharField(help_text='Maximum nubmer of chars: 128', max_length=128, unique=True, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Categiry',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='', force_format=None, help_text='Size: 1280px/720px, png or jpeg format', keep_meta=True, quality=100, scale=None, size=[1280, 720], upload_to='images/products/main', verbose_name='Main Image')),
                ('name', models.CharField(help_text='Maximum nubmer of chars: 225', max_length=225, verbose_name='Product Name')),
                ('description', models.TextField(help_text='Maximum nubmer of chars: 1024', max_length=1024, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=10)),
                ('quantity', models.IntegerField(help_text='Quantity')),
                ('date_added', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Date added')),
                ('visible', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], default='True', max_length=8, verbose_name='Visible?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
