# Generated by Django 5.0.6 on 2024-05-28 14:02

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='', force_format=None, help_text='Size: 1280px/720px, png or jpeg format', keep_meta=True, quality=100, scale=None, size=[1280, 720], upload_to='images/products/main', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Maximum nubmer of chars: 225', max_length=225, verbose_name='Name'),
        ),
    ]
