# Generated by Django 5.0.6 on 2024-05-28 14:41

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='', force_format=None, help_text='Size: 1280px/720px, png or jpeg format', keep_meta=True, quality=100, scale=None, size=[1280, 720], upload_to='media/images/products/', verbose_name='Image'),
        ),
    ]
